name: Generate ASCII Artwork

on:
  [push]

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Checkout Repo Files
      run: ls -ltra

    - name: Execute Cowsay CMD
      run: |
        cd scripts
        chmod +x .ascii-script.sh
        ./ascii-script.sh
